name: Tauri Build & Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"   # 只有打 tag (如 v0.1.0) 才触发发布

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      # 设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: 'npm'

      # 设置 Rust
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # Linux 依赖
      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      # 安装依赖
      - name: Install dependencies
        run: npm install

      # 构建 Tauri 应用
      - name: Build Tauri App
        run: npm run tauri:build

      # 上传 artifact（方便调试用）
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-${{ matrix.platform }}
          path: src-tauri/target/release/bundle/**

      # 上传到 GitHub Release
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: src-tauri/target/release/bundle/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
